# Generated by Django 4.0.6 on 2022-08-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_clientprofilemodel_clientecommerce_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientecommerce',
            old_name='user',
            new_name='client',
        ),
    ]
