# Generated by Django 4.0.6 on 2022-08-06 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_name', models.SlugField(max_length=32, null=True)),
                ('name', models.CharField(max_length=32, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_name', models.SlugField(max_length=32, null=True)),
                ('description', models.TextField(null=True)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('weight', models.CharField(max_length=32, null=True)),
                ('location', models.CharField(max_length=64, null=True)),
                ('name', models.CharField(max_length=5, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('diameter', models.CharField(max_length=25, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.category')),
            ],
        ),
    ]
