# Generated by Django 4.0.6 on 2022-08-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_category_name_remove_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug_name',
            field=models.SlugField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='diameter',
            field=models.CharField(default='not specified', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug_name',
            field=models.SlugField(max_length=32, null=True),
        ),
    ]
